Perform the following operations using R/Python on suitable data sets:

In [1]:
import csv
import pandas as pd
import numpy as np

In [2]:
# a) read data from different formats (like csv, xls)

data = pd.read_csv('/content/Heart.csv')

In [3]:
# b) Find Shape of Data

shape = data.shape
print(shape)

(303, 15)

In [4]:
# c) Find Missing Values

data.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [6]:
# d) Find data type of each column

df = pd.DataFrame(data)
print(df.dtypes)

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [24]:
# e) Finding out Zero's
zero_count = (data == 0).sum()
print("Number of Zero's are = ", zero_count)

Number of Zero's are =  Unnamed: 0      0
Age             0
Sex            97
ChestPain       0
RestBP          0
Chol            0
Fbs           258
RestECG       151
MaxHR           0
ExAng         204
Oldpeak        99
Slope           0
Ca            176
Thal            0
AHD             0
dtype: int64

In [7]:
# f) Indexing and selecting data, sort data,

display(data.head())

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [25]:
# selecting rows by there index

rows = data.iloc[1:5]
print(rows)

   Unnamed: 0   Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
1           2  67.0  1.0  asymptomatic     160   286    0        2    108
2           3  67.0  1.0  asymptomatic     120   229    0        2    129
3           4  37.0  1.0    nonanginal     130   250    0        0    187
4           5  41.0  0.0    nontypical     130   204    0        2    172

   ExAng  Oldpeak  Slope   Ca        Thal  AHD
1      1      1.5      2  3.0      normal  Yes
2      1      2.6      2  2.0  reversable  Yes
3      0      3.5      3  0.0      normal   No
4      0      1.4      1  0.0      normal   No

In [28]:
# sorting

sorted_data = data.sort_values('Age')
print(sorted_data)

     Unnamed: 0   Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
132         133  29.0  1.0    nontypical     130   204    0        2    202
101         102  34.0  1.0       typical     118   182    0        2    174
225         226  34.0  0.0    nontypical     118   210    0        0    192
283         284  35.0  1.0    nontypical     122   192    0        0    174
117         118  35.0  0.0  asymptomatic     138   183    0        0    182
..          ...   ...  ...           ...     ...   ...  ...      ...    ...
42           43  71.0  0.0    nontypical     160   302    0        0    162
103         104  71.0  0.0    nonanginal     110   265    1        2    130
233         234  74.0  0.0    nontypical     120   269    0        2    121
257         258  76.0  0.0    nonanginal     140   197    0        1    116
161         162  77.0  1.0  asymptomatic     125   304    0        2    162

     ExAng  Oldpeak  Slope   Ca    Thal  AHD
132      0      0.0      1  0.0  normal   No
101      0      0.0      1  0.0  normal   No
225      0      0.7      1  0.0  normal   No
283      0      0.0      1  0.0  normal   No
117      0      1.4      1  0.0  normal   No
..     ...      ...    ...  ...     ...  ...
42       0      0.4      1  2.0  normal   No
103      0      0.0      1  1.0  normal   No
233      1      0.2      1  1.0  normal   No
257      0      1.1      2  0.0  normal   No
161      1      0.0      1  3.0  normal  Yes

[303 rows x 15 columns]

In [8]:
# select a single column

first_column = data['Age']
print('First column is selected :')
print(first_column)

First column is selected :
0      63
1      67
2      67
3      37
4      41
       ..
298    45
299    68
300    57
301    57
302    38
Name: Age, Length: 303, dtype: int64

In [10]:
display(first_column.head(5))

0    63
1    67
2    67
3    37
4    41
Name: Age, dtype: int64

In [11]:
# g) Describe attributes of data, checking data types of each column,

data.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,152.000000,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,87.612784,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,76.500000,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,152.000000,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,227.500000,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,303.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [19]:
from enum import unique
# counting unique values of data, format of each column, converting variable  data type (e.g. from long to short, vice versa)

unique_values_Age = data['Age'].unique()
print('Unique values in Ages :')
print(unique_values_Age.sum())

print('Unique values in Sex :')
unique_values_Sex = data['Sex'].unique()
print(unique_values_Sex.sum())

print('Unique values in RestBp :')
unique_values_RestBP = data['RestBP'].unique()
print(unique_values_RestBP.sum())

Unique values in Ages :
2215
Unique values in Sex :
1
Unique values in RestBp :
6853

In [20]:
# Format of Each Column

column_format = data.dtypes
print(column_format)

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [23]:
# Converting variable datatypes
data['Age'] = data['Age'].astype(float)
print('Datatype of Age = ', data['Age'].dtypes)

data['Sex'] = data['Sex'].astype(float)
print('Datatype of Sex = ', data['Sex'].dtypes)

Datatype of Age =  float64
Datatype of Sex =  float64